import type { Listing, User, Transaction, LandlordVerification } from "@/types";

export const MOCK_LANDLORD_VERIFICATIONS: LandlordVerification[] = [
  {
    landlordId: "l3",
    status: "pending",
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const MOCK_LANDLORDS = [
  {
    id: "l1",
    name: "David Ssemwanga",
    phone: "0772100200",
    whatsapp: "256772100200",
    isVerified: true,
    listingsCount: 4,
    joinedAt: "2025-01-15",
  },
  {
    id: "l2",
    name: "Grace Namutebi",
    phone: "0704300100",
    isVerified: true,
    listingsCount: 2,
    joinedAt: "2025-03-10",
  },
  {
    id: "l3",
    name: "Robert Okello",
    phone: "0751400600",
    isVerified: false,
    listingsCount: 1,
    joinedAt: "2026-01-20",
  },
  {
    id: "l4",
    name: "Fatuma Nakato",
    phone: "0782500300",
    isVerified: true,
    listingsCount: 3,
    joinedAt: "2024-11-05",
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "p1",
    landlordId: "l1",
    title: "Modern 2-Bedroom in Kira",
    description: "A spacious and well-finished 2-bedroom apartment in a secure gated compound in Kira. The unit features tiled floors throughout, a modern kitchen, and a large veranda with compound views. Located just 5 minutes from Kira Town on a tarmac road — easy access to shops, schools, and public transport.",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    monthlyRent: 650000,
    deposit: 1300000,
    location: "Kira, Wakiso",
    district: "Wakiso",
    address: "Kira Road, off Kasangati Highway",
    lat: 0.3661,
    lng: 32.6354,
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "security", "parking", "tiled", "veranda", "compound", "gated"],
    rules: ["No pets", "No loud music after 10pm", "No subletting"],
    isFurnished: false,
    totalUnits: 3,
    units: [
      { id: "p1-u1", status: "available" },
      { id: "p1-u2", status: "available" },
      { id: "p1-u3", status: "pending", tenantId: "t1", pendingSince: new Date(Date.now() - 3600000).toISOString() },
    ],
    availableUnits: 2,
    pendingUnits: 1,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 10800000).toISOString(),
    isVerified: true,
    createdAt: "2026-07-01",
    landlord: MOCK_LANDLORDS[0],
    isPaid: true,
  },
  {
    id: "p2",
    landlordId: "l2",
    title: "Self-Contained Room in Ntinda",
    description: "Clean and quiet self-contained single room in Ntinda. Perfect for a working professional or student. Has its own bathroom and kitchen. Water and electricity always available. Very close to Ntinda Shopping Complex.",
    propertyType: "room",
    bedrooms: 1,
    bathrooms: 1,
    monthlyRent: 300000,
    deposit: 300000,
    location: "Ntinda, Kampala",
    district: "Kampala",
    address: "Ntinda Road, near Ntinda Complex",
    lat: 0.3437,
    lng: 32.6167,
    photos: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "tiled", "kitchen"],
    rules: ["No visitors after 9pm", "Quiet environment only"],
    totalUnits: 1,
    units: [{ id: "p2-u1", status: "available" }],
    availableUnits: 1,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 7200000).toISOString(),
    isVerified: true,
    createdAt: "2026-07-15",
    landlord: MOCK_LANDLORDS[1],
    isPaid: true,
  },
  {
    id: "p3",
    landlordId: "l3",
    title: "3-Bedroom House in Najjera",
    description: "A well-maintained 3-bedroom standalone house in Najjera. The house has a large compound ideal for families, an outdoor kitchen area, and a borehole for water supply. Located in a peaceful neighborhood with a generator for backup power.",
    propertyType: "house",
    propertySubtype: "standalone",
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: 1200000,
    deposit: 2400000,
    isFurnished: false,
    location: "Najjera, Wakiso",
    district: "Wakiso",
    address: "Najjera Hill Road",
    lat: 0.3812,
    lng: 32.6410,
    photos: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&auto=format",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "borehole", "generator", "parking", "compound", "kitchen"],
    rules: ["Families only", "No business operations"],
    totalUnits: 1,
    units: [{ id: "p3-u1", status: "available" }],
    availableUnits: 1,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 172800000).toISOString(),
    isVerified: false,
    createdAt: "2026-06-20",
    landlord: MOCK_LANDLORDS[2],
    isPaid: true,
  },
  {
    id: "p4",
    landlordId: "l4",
    title: "Furnished Studio in Bukoto",
    description: "Compact and modern studio apartment in upmarket Bukoto. Comes fully furnished with a bed, sofa, and small dining area. High-speed Wi-Fi included. Very secure building with 24/7 security. Ideal for a single professional.",
    propertyType: "studio",
    bedrooms: 1,
    bathrooms: 1,
    monthlyRent: 800000,
    deposit: 800000,
    isFurnished: true,
    location: "Bukoto, Kampala",
    district: "Kampala",
    address: "Bukoto Street, near Acacia Mall",
    lat: 0.3325,
    lng: 32.5968,
    photos: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&auto=format",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "wifi", "security", "tiled", "furnished", "dsatv"],
    rules: ["No smoking", "No parties"],
    totalUnits: 2,
    units: [
      { id: "p4-u1", status: "available" },
      { id: "p4-u2", status: "available" },
    ],
    availableUnits: 2,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 1800000).toISOString(),
    isVerified: true,
    createdAt: "2026-07-20",
    landlord: MOCK_LANDLORDS[3],
    isPaid: true,
  },
  {
    id: "p5",
    landlordId: "l1",
    title: "2-Bedroom in Naalya Estate",
    description: "Two-bedroom apartment within Naalya Estate. Gated community with 24/7 security, reliable water supply, and standby generator. The apartments are newly built with quality finishes. Walking distance to Naalya Shopping Mall.",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    monthlyRent: 750000,
    deposit: 1500000,
    location: "Naalya, Wakiso",
    district: "Wakiso",
    address: "Naalya Estate, Phase 2",
    lat: 0.3811,
    lng: 32.6233,
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "security", "gated", "parking", "generator", "tiled"],
    rules: ["No smoking indoors", "Keep common areas clean"],
    totalUnits: 5,
    units: [
      { id: "p5-u1", status: "available" },
      { id: "p5-u2", status: "available" },
      { id: "p5-u3", status: "available" },
      { id: "p5-u4", status: "pending", tenantId: "t2", pendingSince: new Date(Date.now() - 14400000).toISOString() },
      { id: "p5-u5", status: "available" },
    ],
    availableUnits: 4,
    pendingUnits: 1,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 5400000).toISOString(),
    isVerified: true,
    createdAt: "2026-05-10",
    landlord: MOCK_LANDLORDS[0],
    isPaid: true,
  },
  {
    id: "p6",
    landlordId: "l4",
    title: "Single Room in Kisaasi",
    description: "Affordable single room in Kisaasi, suitable for a student or young professional. Shared bathroom with only 2 other rooms. Compound is secured and peaceful. Easy access to boda boda stage.",
    propertyType: "room",
    bedrooms: 1,
    bathrooms: 1,
    monthlyRent: 180000,
    deposit: 180000,
    location: "Kisaasi, Kampala",
    district: "Kampala",
    address: "Kisaasi Road, near Total Petrol Station",
    lat: 0.3656,
    lng: 32.6140,
    photos: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "compound"],
    rules: ["Quiet hours after 10pm"],
    totalUnits: 4,
    units: [
      { id: "p6-u1", status: "available" },
      { id: "p6-u2", status: "available" },
      { id: "p6-u3", status: "available" },
      { id: "p6-u4", status: "available" },
    ],
    availableUnits: 4,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 86400000).toISOString(),
    isVerified: false,
    createdAt: "2026-07-25",
    landlord: MOCK_LANDLORDS[3],
    isPaid: true,
  },
  {
    id: "p7",
    landlordId: "l2",
    title: "4-Bedroom Villa in Muyenga",
    description: "Luxurious 4-bedroom villa in the prestigious Muyenga area. The property features a large swimming pool, fully equipped gym, home cinema room, and beautifully landscaped garden. Perfect for expats or senior executives.",
    propertyType: "villa",
    bedrooms: 4,
    bathrooms: 3,
    monthlyRent: 5000000,
    deposit: 10000000,
    isFurnished: true,
    location: "Muyenga, Kampala",
    district: "Kampala",
    address: "Muyenga Tank Hill Road",
    lat: 0.2862,
    lng: 32.6105,
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "wifi", "security", "parking", "generator", "furnished", "dsatv", "compound", "gated"],
    rules: ["Long-term lease preferred (1+ year)", "References required"],
    totalUnits: 1,
    units: [{ id: "p7-u1", status: "available" }],
    availableUnits: 1,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 43200000).toISOString(),
    isVerified: true,
    createdAt: "2026-06-01",
    landlord: MOCK_LANDLORDS[1],
    isPaid: true,
  },
  {
    id: "p8",
    landlordId: "l3",
    title: "3-Bedroom Apartment in Kyanja",
    description: "Spacious 3-bedroom apartment in Kyanja. Modern finishes, reliable water supply, and a great view of the valley. Close to major supermarkets and schools. Ideal for a family of 4–6.",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    monthlyRent: 950000,
    deposit: 1900000,
    location: "Kyanja, Wakiso",
    district: "Wakiso",
    address: "Kyanja Road, off Northern Bypass",
    lat: 0.3902,
    lng: 32.5902,
    photos: [
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&auto=format",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format",
    ],
    amenities: ["water", "electricity", "tiled", "kitchen", "parking", "veranda"],
    rules: ["No smoking", "Families preferred"],
    totalUnits: 2,
    units: [
      { id: "p8-u1", status: "available" },
      { id: "p8-u2", status: "available" },
    ],
    availableUnits: 2,
    pendingUnits: 0,
    rentedUnits: 0,
    lastConfirmedAt: new Date(Date.now() - 28800000).toISOString(),
    isVerified: false,
    createdAt: "2026-07-12",
    landlord: MOCK_LANDLORDS[2],
    isPaid: true,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "t1",
    name: "James Mutebi",
    email: "james.mutebi@gmail.com",
    phone: "0701234567",
    role: "tenant",
    createdAt: "2026-06-01",
  },
  {
    id: "ll1",
    name: "David Ssemwanga",
    email: "david.ssemwanga@gmail.com",
    phone: "0772100200",
    role: "landlord",
    createdAt: "2025-01-15",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "tx1",
    listingId: "p1",
    tenantId: "t1",
    unitId: "p1-u3",
    amount: 2000,
    status: "active",
    unlockedPhone: "0772100200",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    expiresAt: new Date(Date.now() + 169200000).toISOString(),
  },
];
